<?php namespace Backend\Core;
defined("ACCESS") or exit("Access Denied");

use Backend\Controllers\FormRequests;
use Backend\Core\Helper\Actions\FrameworkHelper;
use Backend\Core\PHPJS;
use voku\helper\HtmlMin;


class Router
{
    private $rendered_view = "";


    protected function __construct()
    {
        // Init form requests
        if (class_exists("Backend\Controllers\FormRequests"))
        {
            new FormRequests();
        }

        // Init Framework helper
        if (DISPLAY_HELPER && MAINTENANCE_MODE && $_SESSION["maintenance_access_granted"])
        {
            if (class_exists("Backend\Core\Helper\Actions\FrameworkHelper"))
            {
                new FrameworkHelper();
            }
        }

        // Parse route from url
        $this->getURLRequest();
    }


    private function getURLRequest()
    {
        // Parse page name and variables from the URL
        $root_url = str_replace("index.php", "", $_SERVER["PHP_SELF"]);
        $url = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
        $url = substr($url, strlen($root_url));
        $url = explode("/", $url);
        $page = strtolower($url[0]);
        unset($url[0]);

        // Sanitize the page variable
        $page = htmlspecialchars($page, ENT_QUOTES, 'UTF-8');

        // Validate and sanitize URL variables
        $variables_from_URL = [];
        foreach ($url as $key => $value) {
            $variables_from_URL[$key] = htmlspecialchars($value, ENT_QUOTES, 'UTF-8');
        }

        $this->routeController($page, $variables_from_URL);
    }


    protected function callView($page, $variables = array())
    {
        call_user_func_array(array($this, $page), (array)$variables);
    }


    private function minifyHTML($buffer)
    {
        $minified_HTML = new HtmlMin();
        return $minified_HTML->minify($buffer);
    }


    protected function render($page, array $variables = array())
    {
        // Make sure only one view can be called
        if (!empty($this->rendered_view)) { throw new \Exception("Page: '" . $page . "' can not be rendered because the framework has already rendered page: '" . $this->rendered_view . "'!"); }

        echo "<!-- Page Generated by Kristal Framework -->\n";

        // Include variables passed by the route function
        if (!empty($variables))
        {
            foreach ($variables as $key => $value)
            {
                ${$key} = $value;
            }
        }

        // Include metadata from config.php
        $kristal_metadata = unserialize(METADATA);

        // Start HTML Minification
        if (MINIFY_HTML)
        {
            ob_start(array($this, "minifyHTML"));
        }

        // Include header
        if (!file_exists(page("Base/header.php"))) { throw new \Exception("Failed to build, " . page("Base/header.php") . " was not found!"); }
        include_once page("Base/header.php");

        // Include framework helper
        if (file_exists("App/Backend/Core/FrameworkHelper/frameworkHelper.php") && DISPLAY_HELPER && MAINTENANCE_MODE && $_SESSION["maintenance_access_granted"]) { include_once "App/Backend/Core/FrameworkHelper/frameworkHelper.php"; }

        // Make sure page is a php file
        if (substr($page, -4) !== ".php")
        {
            $page .= ".php";
        }

        // Include the requested page
        if (!file_exists(page($page))) { throw new \Exception("Tried to render page: " . $page . ", but template was not found at " . page($page) . "!"); }
        include_once page($page);

        // Render PHP created javascript variables and code
        PHPJS::release();

        // Render footer
        if (!file_exists(page("Base/footer.php"))) { throw new \Exception("Failed to build, " . page("Base/footer.php") . " was not found!"); }
        include_once page("Base/footer.php");

        // End HTML Minification
        if (MINIFY_HTML)
        {
            ob_end_flush();
        }
        
        $this->rendered_view = $page;
    }
}